title: mskvarci.github.io
description: Your description here
theme: just-the-docs

url: https://mskvarci.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
